---
# tasks file for install_docker
- name: Installing docker
  apt: 
    state: present
    update_cache: yes
    pkg: docker.io

- name: ensure Docker is running
  service: name=docker state=started

- name: Ensure Docker is Running after reboot
  shell: systemctl enable docker

- name: Add permissions for Jenkins User to interact with Docker
  shell: | 
       sudo usermod -a -G docker jenkins
  become: true

- name: Unconditionally reboot the machine with all defaults
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 100
    pre_reboot_delay: 0
    post_reboot_delay: 10
    test_command: whoami
